#define STRIP_BLACK    0

// for RGB Encoding 

#define STRIP_BLUE_VERYLOW   (3 <<  5)  //11      RED
#define STRIP_BLUE_LOW       (15 <<  5)
#define STRIP_BLUE_MEDIUM    (31 << 5)
#define STRIP_BLUE_UP        (63 << 5)
#define STRIP_BLUE_HIGH      0x0000FF 

#define STRIP_RED_VERYLOW  (1 <<  11)   //5     GREEN
#define STRIP_RED_LOW      (7 << 11)  
#define STRIP_RED_MEDIUM   (15 << 11)  
#define STRIP_RED_UP       (31 << 11)
#define STRIP_RED_HIGH     0x00FF00 

#define STRIP_GREEN_VERYLOW  1            //3   1 BLUE
#define STRIP_GREEN_LOW      7            //7  15
#define STRIP_GREEN_MEDIUM   15           //15  31
#define STRIP_GREEN_UP     0xFF0000 
#define STRIP_GREEN_HIGH   0xFF0000         //31  63

#define STRIP_ORANGE_VERYLOW  (STRIP_RED_VERYLOW + STRIP_GREEN_VERYLOW)
#define STRIP_ORANGE_LOW      (STRIP_RED_LOW     + STRIP_GREEN_LOW)
#define STRIP_ORANGE_MEDIUM   (STRIP_RED_MEDIUM  + STRIP_GREEN_MEDIUM)
#define STRIP_ORANGE_HIGH     (STRIP_RED_HIGH    + STRIP_GREEN_HIGH)

#define STRIP_PURPLE_VERYLOW  (STRIP_RED_VERYLOW + STRIP_BLUE_VERYLOW)
#define STRIP_PURPLE_LOW      (STRIP_RED_LOW     + STRIP_BLUE_LOW)
#define STRIP_PURPLE_MEDIUM   (STRIP_RED_MEDIUM  + STRIP_BLUE_MEDIUM)
#define STRIP_PURPLE_HIGH     (STRIP_RED_HIGH    + STRIP_BLUE_HIGH)

#define STRIP_CYAN_VERYLOW    (STRIP_GREEN_VERYLOW + STRIP_BLUE_VERYLOW)
#define STRIP_CYAN_LOW        (STRIP_GREEN_LOW     + STRIP_BLUE_LOW)
#define STRIP_CYAN_MEDIUM     (STRIP_GREEN_MEDIUM  + STRIP_BLUE_MEDIUM)
#define STRIP_CYAN_HIGH       (STRIP_GREEN_HIGH    + STRIP_BLUE_HIGH)

#define STRIP_WHITE_VERYLOW   (STRIP_RED_VERYLOW + STRIP_GREEN_VERYLOW + STRIP_BLUE_VERYLOW)
#define STRIP_WHITE_LOW       (STRIP_RED_LOW     + STRIP_GREEN_LOW     + STRIP_BLUE_LOW)
#define STRIP_WHITE_MEDIUM    (STRIP_RED_MEDIUM  + STRIP_GREEN_MEDIUM  + STRIP_BLUE_MEDIUM)
#define STRIP_WHITE_HIGH      (STRIP_RED_HIGH    + STRIP_GREEN_HIGH    + STRIP_BLUE_HIGH)    

